### ISSUE TITLE
Instructions to setup filebeat

### ISSUE THREAD

**Issue by ScholliYT** [lancachenet/logstash#12]
The current Readme doesn't specify how to setup a Filebeat for pushing the logs from i.e. monolithic to logstash.

My current setup with [lancachenet/docker-compose](https://github.com/lancachenet/docker-compose) looks like this:
- edit `docker-compose.yml` of lancachenet/docker-compose to include
```yml
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.1
    volumes:
      - ${CACHE_ROOT}/logs:/data/logs
      - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
```
where `./config/filebeat/filebeat.yml` is
```yml
name: "lancache"
filebeat.inputs:
- type: log
  paths:
  - '/data/logs/*.log'
  encoding: utf-8
output.logstash:
  hosts: ["logstash_IP:5044"]
  bulk_max_size: 1024
```

This sends the logs from the volume mounted into monolithic via filebeat to logstash where they get processed by the v7 pipeline from #10.
